import { afterEach, expect, test, vi } from 'vitest'
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { CommunicationSection } from '@/features/parents/components/CommunicationSection'
import { clearParentChat, getCommunicationGuides, getParentChat, sendParentChat, type ParentChatSnapshot } from '@/lib/api/communicationApi'
import { ApiError } from '@/lib/api/client'
import { setLocale } from '@/i18n'

vi.mock('@/lib/api/communicationApi', () => ({ getParentChat: vi.fn(), sendParentChat: vi.fn(), clearParentChat: vi.fn(), getCommunicationGuides: vi.fn() }))
vi.mock('@/hooks/useAuthedImage', () => ({ useAuthedImage: () => null }))
afterEach(() => { cleanup(); vi.resetAllMocks(); localStorage.clear(); sessionStorage.clear(); act(() => setLocale('zh')) })
const work = { sourceId: 'tree', createdAt: '2026-09-25T00:00:00Z', imageUrl: null, title: '树', observation: '画面中可以看到树。', evidenceIds: ['OBS-elements'], provenance: 'child' }
const turn = { id: 'request-0001', userText: '我也很累', reply: '每次都得你先忍住，确实很累。', createdAt: '2026-09-26T00:00:00Z', sourceId: null, sources: [] }
const state = (changes = {}): ParentChatSnapshot => ({ revision: 0, available: true, turns: [], memory: { works: [work], scannedCount: 1, limit: 50 }, ...changes })
const start = async (changes = {}) => {
  vi.mocked(getParentChat).mockResolvedValue(state(changes))
  const view = render(<CommunicationSection childName="小朋友" childId="C" token="T" />)
  await screen.findByRole('textbox', { name: '想说的话' })
  await screen.findByText('今天，有什么想聊聊的？')
  return view
}

test('the initial view keeps chat central and does not make unsolicited model calls or repeat the title', async () => {
  await start()
  expect(screen.queryByText('AI 沟通助手')).toBeNull()
  expect(screen.getByText('从画作找个话题').closest('details')?.open).toBe(false)
  expect(getCommunicationGuides).not.toHaveBeenCalled()
  expect(sendParentChat).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: /刚才没忍住/ }))
  const input = screen.getByRole('textbox') as HTMLTextAreaElement
  expect(input.value).toBe('刚才没忍住，冲孩子发了脾气')
  expect(sendParentChat).not.toHaveBeenCalled()
  fireEvent.keyDown(input, { key: 'Enter' })
  expect(sendParentChat).not.toHaveBeenCalled()
  vi.mocked(sendParentChat).mockResolvedValue({ revision: 1, turn })
  fireEvent.click(screen.getByRole('button', { name: '发送' }))
  await screen.findByText(turn.reply)
  expect(sendParentChat).toHaveBeenCalledWith('C', 'T', expect.objectContaining({ text: input.value || '刚才没忍住，冲孩子发了脾气', revision: 0, sourceId: null }), expect.any(AbortSignal))
})

test('artwork selection fills an editable draft and supplies the source only after explicit send', async () => {
  await start()
  fireEvent.click(screen.getByText('孩子的创作'))
  fireEvent.click(screen.getByRole('button', { name: /聊聊这幅画/ }))
  expect((screen.getByRole('textbox') as HTMLTextAreaElement).value).toContain('这幅画')
  expect(screen.getByText('这次聊 · 树')).toBeTruthy()
  expect(sendParentChat).not.toHaveBeenCalled()
  vi.mocked(sendParentChat).mockResolvedValue({ revision: 1, turn: { ...turn, sourceId: 'tree', sources: [work] } })
  fireEvent.click(screen.getByRole('button', { name: '发送' }))
  await screen.findByRole('button', { name: /参考作品/ })
  expect(vi.mocked(sendParentChat).mock.calls[0][2].sourceId).toBe('tree')
})

test('failed messages stay editable and keyboard retry reuses the same request ID', async () => {
  await start()
  vi.mocked(sendParentChat).mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce({ revision: 1, turn })
  fireEvent.change(screen.getByRole('textbox'), { target: { value: '我也很累' } })
  fireEvent.click(screen.getByRole('button', { name: '发送' }))
  await screen.findByRole('alert')
  expect((screen.getByRole('textbox') as HTMLTextAreaElement).value).toBe('我也很累')
  fireEvent.keyDown(screen.getByRole('textbox'), { key: 'Enter', ctrlKey: true })
  await screen.findByText(turn.reply)
  expect(vi.mocked(sendParentChat).mock.calls[1][2]).toEqual(vi.mocked(sendParentChat).mock.calls[0][2])
  expect(screen.queryByRole('alert')).toBeNull()
})

test('switching children aborts pending sends and ignores late answers', async () => {
  const view = await start()
  let finish!: (value: { revision: number; turn: typeof turn }) => void
  vi.mocked(sendParentChat).mockImplementationOnce(() => new Promise(resolve => { finish = resolve }))
  fireEvent.change(screen.getByRole('textbox'), { target: { value: '我也很累' } })
  fireEvent.click(screen.getByRole('button', { name: '发送' }))
  expect(screen.getByRole('status', { name: '正在回复…' })).toBeTruthy()
  view.rerender(<CommunicationSection childName="另一个孩子" childId="B" token="T" />)
  await screen.findByText('今天，有什么想聊聊的？')
  expect(vi.mocked(sendParentChat).mock.calls[0][3]?.aborted).toBe(true)
  await act(async () => finish({ revision: 1, turn }))
  expect(screen.queryByText(turn.reply)).toBeNull()
  expect(getParentChat).toHaveBeenLastCalledWith('B', 'T', 'zh', expect.any(AbortSignal))
})

test('clear requires a deliberate second click and preserves artwork memory', async () => {
  vi.mocked(getParentChat).mockResolvedValue(state({ revision: 1, turns: [turn] }))
  vi.mocked(clearParentChat).mockResolvedValue({ revision: 2 })
  render(<CommunicationSection childName="小朋友" childId="C" token="T" />)
  fireEvent.click(await screen.findByRole('button', { name: '清空聊天' }))
  expect(clearParentChat).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: '确认清空' }))
  await screen.findByText('今天，有什么想聊聊的？')
  expect(clearParentChat).toHaveBeenCalledWith('C', 'T', 1, expect.any(AbortSignal))
  expect(screen.queryByText(turn.reply)).toBeNull()
  fireEvent.click(screen.getByText('孩子的创作'))
  expect(screen.getByText('树')).toBeTruthy()
})

test('stale history reloads without automatically resending; the written message is retained', async () => {
  await start()
  vi.mocked(sendParentChat).mockRejectedValue(new ApiError(409, 'chat_changed'))
  vi.mocked(getParentChat).mockResolvedValue(state({ revision: 2 }))
  fireEvent.change(screen.getByRole('textbox'), { target: { value: '新的问题' } })
  fireEvent.click(screen.getByRole('button', { name: '发送' }))
  await screen.findByText('记录已更新，请确认后再发送。')
  await waitFor(() => expect(getParentChat).toHaveBeenCalledTimes(2))
  expect((screen.getByRole('textbox') as HTMLTextAreaElement).value).toBe('新的问题')
  expect(sendParentChat).toHaveBeenCalledTimes(1)
})

test('guest conversations work without login or API calls, survive reopening, and can be cleared', async () => {
  const view = render(<CommunicationSection childName="小朋友" isGuest />)
  expect(screen.getByRole('textbox').hasAttribute('disabled')).toBe(false)
  expect(screen.queryByRole('link', { name: '登录后聊天' })).toBeNull()
  expect(screen.queryByText(/未配置|登录后可使用|没有连接/)).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: /刚才没忍住/ }))
  fireEvent.click(screen.getByRole('button', { name: '发送' }))
  await screen.findByText('那一下可能是气急了，吼完心里也不太舒服。刚才是发生了什么？')
  fireEvent.change(screen.getByRole('textbox'), { target: { value: '可每次都要我调整，我也很累' } })
  fireEvent.click(screen.getByRole('button', { name: '发送' }))
  const reflection = '每次都得你先忍住，还得琢磨怎么把话说好，确实很累。你也会有不想再讲道理的时候。'
  await screen.findByText(reflection)
  view.unmount()
  render(<CommunicationSection childName="小朋友" isGuest />)
  expect(screen.getByText(reflection)).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: '清空聊天' }))
  fireEvent.click(screen.getByRole('button', { name: '确认清空' }))
  await screen.findByText('今天，有什么想聊聊的？')
  expect(getParentChat).not.toHaveBeenCalled()
  expect(sendParentChat).not.toHaveBeenCalled()
  expect(clearParentChat).not.toHaveBeenCalled()
  fireEvent.click(screen.getByText('孩子的创作'))
  expect(screen.getAllByRole('button', { name: /聊聊这幅画/ })).toHaveLength(4)
})

test('guest artwork references and conversation cards are usable without fetching guides or images', async () => {
  render(<CommunicationSection childName="小朋友" isGuest />)
  fireEvent.click(screen.getByRole('button', { name: /想聊聊孩子最近的画/ }))
  fireEvent.click(screen.getByRole('button', { name: '发送' }))
  await screen.findByText(/最近有那幅小船，还有一片小森林/)
  expect(screen.getAllByRole('button', { name: /参考作品/ })).toHaveLength(2)
  fireEvent.click(screen.getByText('从画作找个话题'))
  const cards = await screen.findAllByRole('button', { name: '聊聊这幅画' })
  fireEvent.click(cards[1])
  expect(screen.getByText('这次聊 · 一片小森林')).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: '发送' }))
  await screen.findByText(/这幅小森林里有树和小花/)
  expect(getCommunicationGuides).not.toHaveBeenCalled()
  expect(getParentChat).not.toHaveBeenCalled()
  expect(sendParentChat).not.toHaveBeenCalled()
})

test('switching from a pending guest reply to a real family aborts it without leaking demo history', async () => {
  const view = render(<CommunicationSection childName="小朋友" isGuest />)
  fireEvent.change(screen.getByRole('textbox'), { target: { value: '我也很累' } })
  fireEvent.click(screen.getByRole('button', { name: '发送' }))
  vi.mocked(getParentChat).mockResolvedValue(state())
  view.rerender(<CommunicationSection childName="小朋友" childId="C" token="T" />)
  await screen.findByText('今天，有什么想聊聊的？')
  await act(async () => { await new Promise(resolve => setTimeout(resolve, 450)) })
  expect(screen.queryByText('我也很累')).toBeNull()
  expect(getParentChat).toHaveBeenCalledOnce()
  expect(sendParentChat).not.toHaveBeenCalled()
})

test('an unconfigured real service stays unavailable and does not fall back to demo responses', async () => {
  vi.mocked(getParentChat).mockResolvedValue(state({ available: false }))
  render(<CommunicationSection childName="小朋友" childId="C" token="T" />)
  await screen.findByText('聊天服务暂未配置，作品建议仍可查看。')
  expect(screen.getByRole('textbox').hasAttribute('disabled')).toBe(true)
  act(() => setLocale('en'))
  await screen.findByText("What's on your mind today?")
  expect(screen.getByRole('textbox', { name: 'Your message' })).toBeTruthy()
})

test('guest history restores conversations and drafts, confirms deletion and persists across sessions', async () => {
  // jsdom does not implement native dialog focus management; browser QA covers it.
  HTMLDialogElement.prototype.showModal = function () { this.setAttribute('open', '') }
  HTMLDialogElement.prototype.close = function () { this.removeAttribute('open') }
  const view = render(<CommunicationSection childName="小朋友" isGuest />)
  fireEvent.change(screen.getByRole('textbox'), { target: { value: '刚才没忍住，冲孩子发了脾气' } })
  fireEvent.click(screen.getByRole('button', { name: '发送' }))
  expect(screen.getByRole('button', { name: '新对话' }).hasAttribute('disabled')).toBe(true)
  expect(screen.getByRole('button', { name: '历史记录' }).hasAttribute('disabled')).toBe(true)
  const reply = '那一下可能是气急了，吼完心里也不太舒服。刚才是发生了什么？'
  await screen.findByText(reply)
  fireEvent.change(screen.getByRole('textbox'), { target: { value: '还没发出去的话' } })
  fireEvent.click(screen.getByRole('button', { name: '新对话' }))
  expect(screen.getByText('今天，有什么想聊聊的？')).toBeTruthy()
  expect((screen.getByRole('textbox') as HTMLTextAreaElement).value).toBe('')
  fireEvent.click(screen.getByRole('button', { name: /想聊聊孩子最近的画/ }))
  fireEvent.click(screen.getByRole('button', { name: '发送' }))
  await screen.findByText(/最近有那幅小船，还有一片小森林/)
  fireEvent.click(screen.getByRole('button', { name: '历史记录' }))
  expect(screen.getByRole('dialog', { name: '历史记录' })).toBeTruthy()
  expect(screen.getAllByRole('button', { name: /^继续对话/ })).toHaveLength(2)
  fireEvent.click(screen.getByRole('button', { name: '继续对话：刚才没忍住，冲孩子发了脾气' }))
  expect(screen.queryByRole('dialog')).toBeNull()
  expect(screen.getByText(reply)).toBeTruthy()
  expect(screen.queryByText(/最近有那幅小船，还有一片小森林/)).toBeNull()
  expect((screen.getByRole('textbox') as HTMLTextAreaElement).value).toBe('还没发出去的话')
  view.unmount(); sessionStorage.clear()
  render(<CommunicationSection childName="小朋友" isGuest />)
  expect(screen.getByText(reply)).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: '历史记录' }))
  fireEvent.click(screen.getByRole('button', { name: '删除对话：刚才没忍住，冲孩子发了脾气' }))
  expect(screen.getAllByRole('button', { name: /^继续对话/ })).toHaveLength(2)
  fireEvent.click(screen.getByRole('button', { name: '取消' }))
  expect(screen.queryByText('删除后，这段对话无法恢复。')).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: '删除对话：刚才没忍住，冲孩子发了脾气' }))
  fireEvent.click(screen.getByRole('button', { name: '确认删除' }))
  expect(screen.getAllByRole('button', { name: /^继续对话/ })).toHaveLength(1)
  fireEvent.click(screen.getByRole('button', { name: '删除对话：想聊聊孩子最近的画' }))
  fireEvent.click(screen.getByRole('button', { name: '确认删除' }))
  expect(screen.getByText('聊过的话，会留在这里')).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: '关闭历史记录' }))
  expect(screen.getByText('今天，有什么想聊聊的？')).toBeTruthy()
  expect(getParentChat).not.toHaveBeenCalled()
  expect(sendParentChat).not.toHaveBeenCalled()
})
